# install node and npm
sudo apt install nodejs npm

# install dependencies
npm init -y
npm install express sprightly --save

# set up pm2 to enable app as a service
sudo npm install pm2@latest -g
pm2 start server.js
pm2 startup
# env command generated by above command:
#sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
pm2 save

# the system should now be rigged to reboot with nginx & expressJS starting automatically
